# Site settings
title: The Lord of the P.I.G.S.
email: lordpigs2015@gmail.com
description: "Fast-paced simulation game for 4 players, where you decide the economic fate of the Republic of Meridia."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thelordofthepigs.com" # the base hostname & protocol for your site
kickstarter: "http://kickstarter.com/the-lord-of-the-pigs"

social:
    twitter: ThLordOfThePIGS
    facebook: thelordofthepigs
    googleplus: 112175587856430848445
    youtube: UCCCYHxBCl9jTglaodnwKyXQ
    disqus: thelordofthepigs

langs:
  en: English
  es: Español
  pt: Português

# Build settings
markdown: kramdown

numPosts: 5
# paginate: 2
# paginate_path: '/blog/page-:num/'
permalink: "/post/:title/"
excerpt_separator: '<!--more-->'

defaults:
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-redirect-from
