# Site settings
title: The Lord of the P.I.G.S.
email: lordpigs2015@gmail.com
description: "Fast-paced simulation game for 4 players, where you decide the economic fate of the Republic of Meridia."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thelordofthepigs.com" # the base hostname & protocol for your site
kickstarter: "http://kickstarter.com/the-lord-of-the-pigs"

# Build settings
markdown: kramdown


paginate: 2
paginate_path: '/blog/page-:num/'
permalink: "/post/:title/"

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-redirect-from