# Site settings
title: The Lord of the P.I.G.S.
email: lordpigs2015@gmail.com
description: "A mobile, multiplayer, card-based game"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thelordofthepigs.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: ":year-:month-:day/:title/"