# Site settings
title: The Lord of the P.I.G.S.
copyright: The Lord of the P.I.G.S.
email: lordpigs2015@gmail.com
description: "Fast-paced simulation game for 4 players, where you decide the economic fate of the Republic of Meridia."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thelordofthepigs.com" # the base hostname & protocol for your site
kickstarter: "http://kickstarter.com/the-lord-of-the-pigs"

social:
    twitter: ThLordOfThePIGS
    facebook: thelordofthepigs
    googleplus: 112175587856430848445
    youtube: UCCCYHxBCl9jTglaodnwKyXQ
    disqus: thelordofthepigs

langs:
  en: English
  es: Español
  pt: Português

# Build settings
markdown: kramdown

numPosts: 5
# paginate: 2
# paginate_path: '/blog/page-:num/'
permalink: "/post/:title/"
excerpt_separator: '<!--more-->'

defaults:
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-redirect-from


# Prose.IO configuration
rooturl: _posts
media: img/posts
metadata:
  _posts:

    # Post Title
    - name: title
      field:
        element: text
        label: title
        help: Post Title
        placeholder: Post Title

    # Post Language
    - name: lang
      field:
        element: select
        label: lang
        help: Post Lnaguage
        placeholder: Post Lnaguage
        options:
          - name: English
            value: en
          - name: Spanish
            value: es
          - name: Portuguese
            value: pt

    # Is Main?
    - name: is_main
      field:
        element: button
        label: is_main
        help: Is this post the main one?
        on: Yes
        off: No

    # Post Permalink
    - name: permalink
      field:
        element: text
        label: permalink
        help: Permalink (should include language: /en/post/title-of-the-post/)
        placeholder: Post Permalink (/LANG/post/TITLE/)