# Site settings
title: The Lord of the P.I.G.S.
copyright: The Lord of the P.I.G.S.
email: lordpigs2015@gmail.com
description: "Fast-paced simulation game for 4 players, where you decide the economic fate of the Republic of Meridia."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thelordofthepigs.com" # the base hostname & protocol for your site
kickstarter: "http://kickstarter.com/the-lord-of-the-pigs"

googleAnalytics: UA-56278601-1
social:
    twitter: ThLordOfThePIGS
    facebook: thelordofthepigs
    googleplus: 112175587856430848445
    youtube: UCCCYHxBCl9jTglaodnwKyXQ
    disqus: thelordofthepigs

langs:
  en: English
  es: Español
  it: Italiano
  pt: Português

# Build settings
markdown: kramdown

numPosts: 5
# paginate: 2
# paginate_path: '/blog/page-:num/'
permalink: "/post/:title/"
excerpt_separator: '<!--more-->'

defaults:
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-redirect-from

exclude: [Gemfile, vendor, '_vendor']


# Prose.IO configuration
prose:
#  rooturl: _posts
  media: media
  metadata:
    _posts:
      - name: title
        field:
          element: text
          label: Post Title

      - name: lang
        field:
          element: select
          label: Post Language
          help: Language in which the post it written.
          options:
            - name: English
              value: en
            - name: Italian
              value: it
            - name: Portuguese
              value: pt
            - name: Spanish
              value: es
      - name: is_main
        field:
          element: checkbox
          label: Main Post
          help: Check if this post should be the main of the group.
          value: false
      - name: permalink
        field:
          element: text
          label: Permalink
          help: |
            Post path. Use format /&lt;lang&gt;/posts/&lt;title&gt;/
            (without the angle brackets). ALWAYS ADD A TRAILING SLASH.
          placeholder: /__/posts/__________/

      # One per language
      - name: lang_en_link
        field:
          element: text
          label: English Version Permalink
          help: |
            The permalink of the English version of this post.
            If this is the English version or the post does not have
            an English version, leave blank. ALWAYS ADD A TRAILING SLASH.
          placeholder: /en/posts/__________/

      - name: lang_es_link
        field:
          element: text
          label: Spanish Version Permalink
          help: |
            The permalink of the Spanish version of this post.
            If this is the Spanish version or the post does not have
            an Spanish version, leave blank. ALWAYS ADD A TRAILING SLASH.
          placeholder: /es/posts/__________/

      - name: lang_pt_link
        field:
          element: text
          label: Portuguese Version Permalink
          help: |
            The permalink of the Portuguese version of this post.
            If this is the Portuguese version or the post does not have
            an Portuguese version, leave blank. ALWAYS ADD A TRAILING SLASH.
          placeholder: /pt/posts/__________/

      - name: lang_it_link
        field:
          element: text
          label: Italian Version Permalink
          help: |
            The permalink of the Italian version of this post.
            If this is the Italian version or the post does not have
            an Italian version, leave blank. ALWAYS ADD A TRAILING SLASH.
          placeholder: /it/posts/__________/
